Repository decodingafterlife/SweetCode, pull requests merged in 2025-08, with the labels that each got.

#19 Updated README.md closes #16
  README.md
Labels: gssoc25, level 1

#17 Implemented LeetCode-themed UI with settings and responsive design. Closes #11
  Images/settings-svgrepo-com.svg
  background.js
  blocked.html
  manifest.json
  popup.css
  popup.html
  popup.js
Labels: gssoc25, level 3

#26 created issue template
  .github/Issue_template/bug_report.md
  .github/Issue_template/config.yml
  .github/Issue_template/documentation_issue.md
  .github/Issue_template/feature_request.md
Labels: gssoc25, level 1

#21 Add customizable reset period and prevent time stacking
  background.js
  popup.html
  popup.js
Labels: gssoc25, level 2
